import { IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import React from "react";

const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-ibm-plex-serif'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSerif.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
